"""initial

Revision ID: 106fd094c549
Revises: 
Create Date: 2026-04-12 12:12:19.207662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106fd094c549'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('senha_hash', sa.String(
                        length=255), nullable=False),
                    sa.Column('telefone', sa.String(length=20), nullable=True),
                    sa.Column('role', sa.Enum('cliente', 'profissional',
                                              'admin_loja', name='roleenum'), nullable=False),
                    sa.Column('accepted_terms_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('accepted_terms_version',
                              sa.String(length=10), nullable=True),
                    sa.Column('anonymized_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('lojas',
                    sa.Column('owner_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('descricao', sa.Text(), nullable=True),
                    sa.Column('telefone', sa.String(length=20), nullable=True),
                    sa.Column('email', sa.String(length=255), nullable=True),
                    sa.Column('endereco', sa.String(
                        length=255), nullable=True),
                    sa.Column('logo_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['owner_id'], ['usuarios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('profissionais',
                    sa.Column('usuario_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('loja_id', sa.String(length=26), nullable=False),
                    sa.Column('bio', sa.Text(), nullable=True),
                    sa.Column('foto_url', sa.String(
                        length=500), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ),
                    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('horarios_trabalho',
                    sa.Column('profissional_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('dia_semana', sa.Integer(), nullable=False),
                    sa.Column('hora_inicio', sa.Time(), nullable=False),
                    sa.Column('hora_fim', sa.Time(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.ForeignKeyConstraint(['profissional_id'], [
                                            'profissionais.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('servicos',
                    sa.Column('profissional_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('nome', sa.String(length=100), nullable=False),
                    sa.Column('descricao', sa.Text(), nullable=True),
                    sa.Column('preco', sa.Numeric(
                        precision=10, scale=2), nullable=False),
                    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['profissional_id'], [
                                            'profissionais.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('agendamentos',
                    sa.Column('cliente_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('profissional_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('servico_id', sa.String(
                        length=26), nullable=False),
                    sa.Column('data_hora_inicio', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('data_hora_fim', sa.DateTime(
                        timezone=True), nullable=False),
                    sa.Column('status', sa.Enum('pendente', 'confirmado',
                                                'cancelado', 'concluido', name='statusenum'), nullable=False),
                    sa.Column('notas', sa.Text(), nullable=True),
                    sa.Column('cancelado_por', sa.String(
                        length=26), nullable=True),
                    sa.Column('cancelado_motivo', sa.Text(), nullable=True),
                    sa.Column('lembrete_enviado',
                              sa.Boolean(), nullable=False),
                    sa.Column('id', sa.String(length=26), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('deleted_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['cliente_id'], ['usuarios.id'], ),
                    sa.ForeignKeyConstraint(['profissional_id'], [
                                            'profissionais.id'], ),
                    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamentos')
    op.drop_table('servicos')
    op.drop_table('horarios_trabalho')
    op.drop_table('profissionais')
    op.drop_table('lojas')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
