"""create notifications table

Revision ID: 51c56dcaa5ee
Revises: 62858ad91afe
Create Date: 2026-05-09 19:26:12.800045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c56dcaa5ee'
down_revision: Union[str, Sequence[str], None] = '62858ad91afe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('notification_type', sa.Enum('reminder', 'confirmation', 'cancellation', 'evaluation', name='notificationtype'), nullable=False),
    sa.Column('channel', sa.Enum('reminder', 'confirmation', 'cancellation', 'evaluation', name='notificationtype'), nullable=False),
    sa.Column('recipient_id', sa.String(length=26), nullable=False),
    sa.Column('recipient_type', sa.Enum('customer', 'professional', name='recipienttype'), nullable=False),
    sa.Column('appointment_id', sa.String(length=26), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    # ### end Alembic commands ###
