"""create notifications table

Revision ID: 62858ad91afe
Revises: 18a779368dd3
Create Date: 2026-05-09 19:08:18.958783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62858ad91afe'
down_revision: Union[str, Sequence[str], None] = '18a779368dd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('professional_invites_token_key'), 'professional_invites', type_='unique')
    op.drop_index(op.f('ix_professional_invites_token'), table_name='professional_invites')
    op.create_index(op.f('ix_professional_invites_token'), 'professional_invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_invites_token'), table_name='professional_invites')
    op.create_index(op.f('ix_professional_invites_token'), 'professional_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('professional_invites_token_key'), 'professional_invites', ['token'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
