"""add_banner_url_to_stores

Revision ID: af42c19fe183
Revises: ed48ea967003
Create Date: 2026-06-27 15:22:19.593038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af42c19fe183'
down_revision: Union[str, Sequence[str], None] = 'ed48ea967003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('banner_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'banner_url')
    # ### end Alembic commands ###
