"""work_schedule_times_without_timezone

Revision ID: c377585b02a8
Revises: af42c19fe183
Create Date: 2026-06-27 18:48:15.040857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c377585b02a8'
down_revision: Union[str, Sequence[str], None] = 'af42c19fe183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_schedules', 'start_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False,
               postgresql_using='start_time::time')
    op.alter_column('work_schedules', 'end_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False,
               postgresql_using='end_time::time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_schedules', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('work_schedules', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
