"""work_schedule_times_with_timezone

Revision ID: ed48ea967003
Revises: e1f2a3b4c5d6
Create Date: 2026-06-23 22:05:10.834363

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed48ea967003'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_invites_token'), table_name='professional_invites')
    op.drop_table('professional_invites')
    op.alter_column('appointments', 'service_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=False)
    op.alter_column('appointments', 'store_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=False)
    op.alter_column('professionals', 'store_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=False)
    op.alter_column('work_schedules', 'professional_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=False)
    op.alter_column('work_schedules', 'start_time',
                    existing_type=postgresql.TIME(),
                    type_=sa.Time(timezone=True),
                    existing_nullable=False,
                    postgresql_using="start_time AT TIME ZONE 'UTC'")
    op.alter_column('work_schedules', 'end_time',
                    existing_type=postgresql.TIME(),
                    type_=sa.Time(timezone=True),
                    existing_nullable=False,
                    postgresql_using="end_time AT TIME ZONE 'UTC'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('work_schedules', 'end_time',
                    existing_type=sa.Time(timezone=True),
                    type_=postgresql.TIME(),
                    existing_nullable=False)
    op.alter_column('work_schedules', 'start_time',
                    existing_type=sa.Time(timezone=True),
                    type_=postgresql.TIME(),
                    existing_nullable=False)
    op.alter_column('work_schedules', 'professional_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=True)
    op.alter_column('professionals', 'store_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=True)
    op.alter_column('appointments', 'store_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=True)
    op.alter_column('appointments', 'service_id',
                    existing_type=sa.VARCHAR(length=26),
                    nullable=True)
    op.create_table('professional_invites',
                    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('store_id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
                    sa.Column('created_by', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
                    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
                    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.Column('accepted_user_id', sa.VARCHAR(length=26), autoincrement=False, nullable=True),
                    sa.Column('id', sa.VARCHAR(length=26), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'),
                              autoincrement=False, nullable=False),
                    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['accepted_user_id'], ['users.id'],
                                            name=op.f('professional_invites_accepted_user_id_fkey')),
                    sa.ForeignKeyConstraint(['created_by'], ['users.id'],
                                            name=op.f('professional_invites_created_by_fkey')),
                    sa.ForeignKeyConstraint(['store_id'], ['stores.id'],
                                            name=op.f('professional_invites_store_id_fkey')),
                    sa.PrimaryKeyConstraint('id', name=op.f('professional_invites_pkey'))
                    )
    op.create_index(op.f('ix_professional_invites_token'), 'professional_invites', ['token'], unique=True)
    # ### end Alembic commands ###
